#!/usr/bin/env python3
"""Regenerate the demo tree used for hands-on testing.

    python maint/make_demo.py            # -> /tmp/tmeld-demo
    python maint/make_demo.py --dest DIR

Produces:

    project-a/ project-b/   folder comparison (name filters, VC metadata,
                            missing files both ways, a nested tree)
      src/engine.py         ~1500 lines, ~90 chunks: the scrolling workout
      src/main.py           tiny, for quick screenshots
    merge/                  3-way merge with real conflicts
    repo/                   a git working copy for `tmeld .`

engine.py is built so every rendering path shows up, spread over enough lines
that the panes actually scroll and the two sides drift apart:

  * pure inserts   (one side has no lines -> the thin insert marker)
  * pure deletes
  * single-line and multi-line replaces
  * inline-only edits (one token changed, for the intra-line highlight)
  * a chunk on the very first line and one at EOF
  * over-long lines (horizontal scrolling)
  * long unchanged runs, so sync-scroll has to interpolate
  * a cluster of adjacent chunks, to crowd the linkmap
"""

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

# Cycle of mutations applied to successive sections of engine.py. Fixed order
# rather than random, so a bug found today is still there tomorrow.
MUTATIONS = [
    "same", "line", "insert", "delete", "block",
    "same", "same", "same",          # a long identical run: sync-scroll has to
                                     # interpolate across it
    "inline", "long", "same", "cluster",
]


def section(i: int) -> list:
    """One ~13-line unit of plausible source."""
    return [
        f"",
        f"def handler_{i:03d}(payload, *, retries=3):",
        f'    """Handle event {i} and return a normalised record."""',
        f"    if not payload:",
        f"        raise ValueError('handler_{i:03d}: empty payload')",
        f"    record = {{",
        f"        'kind': 'event_{i:03d}',",
        f"        'weight': {i * 7 % 97},",
        f"        'retries': retries,",
        f"    }}",
        f"    for attempt in range(retries):",
        f"        if dispatch(record, attempt):",
        f"            return record",
        f"    return None",
    ]


def build_engine(n_sections=110):
    """Return (a_lines, b_lines) for src/engine.py."""
    a, b = [], []

    # A chunk on the very first line: the top boundary is a common off-by-one,
    # and a chunk starting at line 0 has no line above it to anchor against.
    a += ["# engine.py (side A) - generated by maint/make_demo.py"]
    b += ["# engine.py (side B) - generated by maint/make_demo.py",
          "# regenerate with: python maint/make_demo.py"]
    a += ["", "from runtime import dispatch", ""]
    b += ["", "from runtime import dispatch", ""]

    for i in range(n_sections):
        lines = section(i)
        kind = MUTATIONS[i % len(MUTATIONS)]

        if kind == "same":
            a += lines
            b += lines

        elif kind == "line":                      # single-line replace
            a += lines
            b += lines[:7] + [f"        'kind': 'EVENT_{i:03d}',"] + lines[8:]

        elif kind == "insert":                    # B gains lines, A gets a marker
            a += lines
            b += lines[:10] + [
                f"    log.debug('handler_{i:03d} start')",
                f"    metrics.incr('handler_{i:03d}')",
                f"    trace.mark({i})",
            ] + lines[10:]

        elif kind == "delete":                    # A has lines B does not
            a += lines
            b += lines[:3] + lines[5:]

        elif kind == "block":                     # multi-line replace
            a += lines
            b += lines[:10] + [
                "    with span('dispatch'):",
                "        for attempt in range(retries):",
                "            if dispatch(record, attempt):",
                "                return record",
                "    return None",
            ]

        elif kind == "inline":                    # one token differs
            a += lines
            b += lines[:8] + [f"        'weight': {i * 7 % 97 + 1},"] + lines[9:]

        elif kind == "long":                      # horizontal scrolling
            tail_a = " ".join(f"arg{j}=None," for j in range(28))
            tail_b = " ".join(f"arg{j}=0," for j in range(28))
            a += lines + [f"    configure_{i:03d}({tail_a} trailing=True)"]
            b += lines + [f"    configure_{i:03d}({tail_b} trailing=False)"]

        elif kind == "cluster":
            # Three chunks separated by a single identical line each: the
            # tightest packing the differ will not merge, so the linkmap has to
            # draw connectors that nearly touch.
            a += (lines[:4] + ["    a_only_1 = 1", "    a_only_2 = 2"]
                  + lines[4:5] + ["    a_only_3 = 3"] + lines[5:])
            b += (lines[:4] + ["    b_only_1 = 1"]
                  + lines[4:5] + ["    b_only_2 = 2", "    b_only_3 = 3"]
                  + lines[5:])

    # A chunk at EOF: B appends, so A's marker hangs off its last line.
    a += ["", "# end of engine.py"]
    b += ["", "# end of engine.py", "", "def teardown():", "    flush()"]
    return a, b


def write(path: Path, lines):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def build_projects(dest: Path):
    a, b = dest / "project-a", dest / "project-b"

    engine_a, engine_b = build_engine()
    write(a / "src/engine.py", engine_a)
    write(b / "src/engine.py", engine_b)

    write(a / "src/main.py", ["def main():", "    print('hello')", "    return 0"])
    write(b / "src/main.py",
          ["def main():", "    print('hello, world')", "    log()", "    return 0"])

    for side in (a, b):
        write(side / "README.md", ["# demo project", "", "shared readme"])
        write(side / "src/__init__.py", [])
        write(side / "src/util/config.py",
              ["TIMEOUT = 30", "RETRIES = 3" if side is a else "RETRIES = 5"])
    write(a / "docs/guide.md", ["# guide", "", "same in both"])
    write(b / "docs/guide.md", ["# guide", "", "same in both"])

    # only-on-one-side entries, and things the default filters must hide
    write(a / "src/legacy.py", ["# removed in b", "def old(): pass"])
    write(a / "docs/old-notes.txt", ["a-only notes"])
    write(b / "src/util/helpers.py", ["def helper(): return 1"])
    write(b / "tests/test_main.py", ["def test_main(): assert True"])
    write(a / "notes.txt~", ["backup junk"])              # filtered
    write(a / "src/main.pyc", ["binary junk"])            # filtered
    write(b / ".git/config", ["[core]"])                  # filtered


def build_merge(dest: Path):
    """3-way: some changes merge cleanly (Alt+M), some genuinely conflict."""
    base, local, remote = [], [], []
    for i in range(40):
        line = f"setting_{i:02d} = {i}"
        if i % 9 == 0:            # both sides edit -> conflict
            base.append(line)
            local.append(f"setting_{i:02d} = LOCAL")
            remote.append(f"setting_{i:02d} = REMOTE")
        elif i % 5 == 0:          # local only -> merges cleanly
            base.append(line)
            local.append(f"setting_{i:02d} = {i * 10}")
            remote.append(line)
        elif i % 7 == 0:          # remote only -> merges cleanly
            base.append(line)
            local.append(line)
            remote.append(f"setting_{i:02d} = {i * 100}")
        else:
            base.append(line); local.append(line); remote.append(line)

    write(dest / "merge/base.py", base)
    write(dest / "merge/local.py", local)
    write(dest / "merge/remote.py", remote)


def build_repo(dest: Path):
    """A git working copy, for `tmeld .` / `bmeld .`."""
    repo = dest / "repo"
    repo.mkdir(parents=True, exist_ok=True)
    run = lambda *c: subprocess.run(c, cwd=repo, check=True,
                                    capture_output=True)
    run("git", "init", "-q")
    run("git", "config", "user.email", "demo@example.com")
    run("git", "config", "user.name", "demo")
    write(repo / "app.py", ["def main():", "    print('hello')", "    return 0"])
    write(repo / "stable.py", ["UNCHANGED = True"])
    run("git", "add", "-A")
    run("git", "commit", "-qm", "initial")
    # working-copy edits: modified, plus an untracked file
    write(repo / "app.py",
          ["def main():", "    print('hello, world')", "    log()", "    return 0"])
    write(repo / "scratch.py", ["# untracked"])


def report(dest: Path):
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
    from tmeld.comparison import Comparison

    a = dest / "project-a/src/engine.py"
    b = dest / "project-b/src/engine.py"
    c = Comparison([str(a), str(b)])
    chunks = c.pane_chunks(0)
    kinds = {}
    empty = 0
    for ch in chunks:
        kinds[ch.tag] = kinds.get(ch.tag, 0) + 1
        if ch.start_a == ch.end_a:
            empty += 1
    longest = max(len(line) for line in c.lines[0] + c.lines[1])

    m = Comparison([str(dest / "merge/local.py"),
                    str(dest / "merge/base.py"),
                    str(dest / "merge/remote.py")])

    print(f"\nengine.py   {len(c.lines[0])} / {len(c.lines[1])} lines")
    print(f"            {c.differ.diff_count()} changes  {dict(sorted(kinds.items()))}")
    print(f"            {empty} zero-height (insert markers), longest line {longest} cols")
    print(f"merge/      {m.differ.diff_count()} changes, "
          f"{len(m.differ.conflicts)} conflicts")


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--dest", default="/tmp/tmeld-demo")
    args = ap.parse_args()

    dest = Path(args.dest)
    shutil.rmtree(dest, ignore_errors=True)
    dest.mkdir(parents=True)

    build_projects(dest)
    build_merge(dest)
    build_repo(dest)
    report(dest)

    print(f"""
Try it:
  tmeld {dest}/project-a {dest}/project-b        # folder compare, Enter on engine.py
  tmeld {dest}/project-{{a,b}}/src/engine.py        # the scrolling workout
  tmeld {dest}/merge/{{local,base,remote}}.py       # 3-way, Alt+M then Ctrl+K
  cd {dest}/repo && tmeld .                       # version control view

Swap `tmeld` for `bmeld` for the browser.""")


if __name__ == "__main__":
    main()
